package frontend.pages;
  /**
   *
   * @author Evan Mcphee
   */
  public class ProfHome extends Page {

      /**
       * Creates new form ProfHome
       */
      public ProfHome() {
          initComponents();
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
           */
          try {
              for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                  if ("Nimbus".equals(info.getName())) {
                      javax.swing.UIManager.setLookAndFeel(info.getClassName());
                      break;
                  }
              }
          } catch (ClassNotFoundException ex) {
              java.util.logging.Logger.getLogger(ProfHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
              java.util.logging.Logger.getLogger(ProfHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
              java.util.logging.Logger.getLogger(ProfHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
              java.util.logging.Logger.getLogger(ProfHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>
      }

      /**
       * This method is called from within the constructor to initialize the form.
       * WARNING: Do NOT modify this code. The content of this method is always
       * regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">
      private void initComponents() {

          jPanel2 = new javax.swing.JPanel();
          deActivateCourseB = new javax.swing.JButton();
          logoutB = new javax.swing.JButton();
          viewCourseB = new javax.swing.JButton();
          activateCourseB = new javax.swing.JButton();
          jLabel2 = new javax.swing.JLabel();
          jScrollPane1 = new javax.swing.JScrollPane();
          courseList = new javax.swing.JList<>();
          addCourseB = new javax.swing.JButton();
          removeCourseB = new javax.swing.JButton();
          jPanel1 = new javax.swing.JPanel();
          userLabel = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setTitle("HomePage");
          setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
          setName("HomePage"); // NOI18N

          jPanel2.setBackground(java.awt.Color.orange);

          deActivateCourseB.setText("Deactivate Course");

          logoutB.setText("Logout");

          viewCourseB.setText("View Course");

          activateCourseB.setText("Activate Course");

          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel2.setText("Your Courses:");

          courseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
          courseList.setModel(new javax.swing.AbstractListModel<String>() {
              String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
              public int getSize() { return strings.length; }
              public String getElementAt(int i) { return strings[i]; }
          });
          jScrollPane1.setViewportView(courseList);

          addCourseB.setText("Add Course");

          removeCourseB.setText("Remove Course");

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
                  jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                  .addContainerGap()
                                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                          .addComponent(deActivateCourseB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(activateCourseB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(viewCourseB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(removeCourseB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(addCourseB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                  .addGap(18, 18, 18)
                                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                          .addGroup(jPanel2Layout.createSequentialGroup()
                                  .addGap(461, 461, 461)
                                  .addComponent(jLabel2)
                                  .addGap(0, 0, Short.MAX_VALUE))
                          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                  .addComponent(logoutB)
                                  .addContainerGap())
          );
          jPanel2Layout.setVerticalGroup(
                  jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addGroup(jPanel2Layout.createSequentialGroup()
                                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(jPanel2Layout.createSequentialGroup()
                                                  .addGap(172, 172, 172)
                                                  .addComponent(viewCourseB)
                                                  .addGap(53, 53, 53)
                                                  .addComponent(activateCourseB)
                                                  .addGap(18, 18, 18)
                                                  .addComponent(deActivateCourseB)
                                                  .addGap(68, 68, 68)
                                                  .addComponent(addCourseB)
                                                  .addGap(18, 18, 18)
                                                  .addComponent(removeCourseB)
                                                  .addGap(0, 12, Short.MAX_VALUE))
                                          .addGroup(jPanel2Layout.createSequentialGroup()
                                                  .addGap(62, 62, 62)
                                                  .addComponent(jLabel2)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                  .addComponent(jScrollPane1)))
                                  .addGap(68, 68, 68)
                                  .addComponent(logoutB)
                                  .addContainerGap())
          );

          jPanel1.setBackground(java.awt.Color.pink);

          userLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          userLabel.setText("User:");

          jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
          jLabel3.setText("Home Page");

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addGroup(jPanel1Layout.createSequentialGroup()
                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                  .addGap(453, 453, 453)
                                                  .addComponent(jLabel3))
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                  .addGap(343, 343, 343)
                                                  .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                  .addContainerGap(383, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                  .addGap(27, 27, 27)
                                  .addComponent(jLabel3)
                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                  .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                  .addGap(25, 25, 25))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                  .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                  .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          );

          pack();
      }// </editor-fold>




      // Variables declaration - do not modify
      private javax.swing.JButton activateCourseB;
      private javax.swing.JButton addCourseB;
      private javax.swing.JList<String> courseList;
      private javax.swing.JButton deActivateCourseB;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel2;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JScrollPane jScrollPane2;
      private javax.swing.JButton logoutB;
      private javax.swing.JButton removeCourseB;
      private javax.swing.JLabel userLabel;
      private javax.swing.JButton viewCourseB;
      // End of variables declaration
  }
